version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dragqueens
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    build: .
    environment:
      - CONNECTION_URL=jdbc:postgresql://postgres:5432/dragqueens
      - USER=postgres
      - PASSWORD=root
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - mynetwork

networks:
  mynetwork:
